runtime: nodejs20

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2

env_variables:
  NODE_ENV: production
  MONGO_URI: mongodb+srv://senitha200109:seni0109@cluster0.pxvzl45.mongodb.net/sunrise_gadgets
