runtime: nodejs22

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2

env_variables:
  NODE_ENV: production
  MONGO_URI: mongodb+srv://senitha200109:K6sssO9gbW3kj8Bw@cluster0.pxvzl45.mongodb.net/sunrise_gadgets?retryWrites=true&w=majority
  JWT_SECRET: sunrise_gadgets_jwt_secret_89f1729b1284a_lk
  ADMIN_SETUP_KEY: sunrise_setup_key_2026_x89a
  CLOUDINARY_CLOUD_NAME: dcpsl0aud
  CLOUDINARY_API_KEY: "992212981231368"
  CLOUDINARY_API_SECRET: i27QwWzK3VqLFZ0os0bXI0zL2IQ
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: "587"
  EMAIL_USER: sunrisegadgetsstore.lk@gmail.com
  EMAIL_PASS: "tysa dqmw ggeb cvjt"
  ADMIN_EMAIL: sunrisegadgetsstore.lk@gmail.com
  FRONTEND_URL: https://euphonious-mousse-b95cd0.netlify.app/
